/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { UnoButtonVariant } from "./components/uno-button/uno-button";
export namespace Components {
    interface UnoButton {
        /**
          * add button variant
         */
        "variant": UnoButtonVariant;
    }
}
declare global {
    interface HTMLUnoButtonElement extends Components.UnoButton, HTMLStencilElement {
    }
    var HTMLUnoButtonElement: {
        prototype: HTMLUnoButtonElement;
        new (): HTMLUnoButtonElement;
    };
    interface HTMLElementTagNameMap {
        "uno-button": HTMLUnoButtonElement;
    }
}
declare namespace LocalJSX {
    interface UnoButton {
        /**
          * add button variant
         */
        "variant"?: UnoButtonVariant;
    }
    interface IntrinsicElements {
        "uno-button": UnoButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uno-button": LocalJSX.UnoButton & JSXBase.HTMLAttributes<HTMLUnoButtonElement>;
        }
    }
}
